background = #1e2125
foreground = #f0e9ec

cursor-color = #f0e9ec
cursor-text = #1e2125

selection-background = #f0e9ec
selection-foreground = #1e2125

palette = 0=#1e2125
palette = 1=#976870
palette = 2=#B4756B
palette = 3=#C17A6A
palette = 4=#9B826B
palette = 5=#B48162
palette = 6=#706B82
palette = 7=#c5aeb9
palette = 8=#897981
palette = 9=#c1a4a9
palette = 10=#d6b4af
palette = 11=#dfbab2
palette = 12=#c4b5a8
palette = 13=#d5b8a7
palette = 14=#a5a1b2
palette = 15=#f0e9ec
