# Primary colors
foreground #f0e9ec
background #1e2125

# Cursor colors
cursor #f0e9ec
cursor_text_color #1e2125

# Selection colors
selection_foreground #1e2125
selection_background #f0e9ec

# URL underline color when hovering with mouse
url_color #706b82

# Kitty window border colors and terminal bell colors (optional)
active_border_color #f0e9ec
inactive_border_color #897981
bell_border_color #C17A6A

# Tab bar colors
active_tab_foreground #1e2125
active_tab_background #f0e9ec
inactive_tab_foreground #897981
inactive_tab_background #1e2125

# Colors for marks (marked text in the terminal)
mark1_foreground #1e2125
mark1_background #9B826B
mark2_foreground #1e2125
mark2_background #B48162
mark3_foreground #1e2125
mark3_background #706B82

# Normal colors
color0 #1e2125
color1 #976870
color2 #B4756B
color3 #C17A6A
color4 #9B826B
color5 #B48162
color6 #706B82
color7 #c5aeb9

# Bright colors
color8 #897981
color9 #c1a4a9
color10 #d6b4af
color11 #dfbab2
color12 #c4b5a8
color13 #d5b8a7
color14 #a5a1b2
color15 #f0e9ec
